### ISSUE TITLE
Config Depo

### ISSUE THREAD

**Issue by NicolasGlassey** [Enelg52/Go_Cloud_Monitoring#1]
@Enelg52 

Bonjour Yann,

Pourriez-vous :
[] activer l'option wiki ?
Il faudra passer le dépôt en public afin de pouvoir l'activer sans frais.

[] me donner les droits "write" ?
https://docs.github.com/en/organizations/managing-user-access-to-your-organizations-repositories/repository-roles-for-an-organization

Je vous propose une approche "monorepo" même si nous allons développer plusieurs modules. Dans ce sens, pourriez-vous renommer le dépôt "Go_Cloud_Monitoring" (car l'idée est de produire du code qui sera adaptable pour n'importe quel cloud).

Nicolas

**Comment by Enelg52** [comment]
C'est fait !
