### ISSUE TITLE
Start/Stop Instances - exceptions

### ISSUE THREAD

**Issue by NicolasGlassey** [Enelg52/Go_Cloud_Monitoring#4]
@Enelg52 

[] startInstance_wrongInstanceId_throwException (instance not found)
[] startInstance_badRegion_throwException (instance not found)
[] startInstance_alreadyStarted_throwException (instance already in expected state)

Same case for StopInstance method.

UML will be updated in few minutes....

**Comment by Enelg52** [comment]
Should be done now.
https://github.com/Enelg52/Go_Cloud_Monitoring/tree/feature/ListEc2
